// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8U8PMr9xmlXAFL2guYzoMDwgRiVAmoOo',
    appId: '1:770152763239:web:24114e4f36d2bcbc1ca9c2',
    messagingSenderId: '770152763239',
    projectId: 'devolveolivro',
    authDomain: 'devolveolivro.firebaseapp.com',
    storageBucket: 'devolveolivro.appspot.com',
    measurementId: 'G-Q6H3VH56NS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpfvLFTxGL454sogcdWLyWBuPOW6Q_vPg',
    appId: '1:770152763239:android:a60af9c2e2a3eda01ca9c2',
    messagingSenderId: '770152763239',
    projectId: 'devolveolivro',
    storageBucket: 'devolveolivro.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTmR84lRl1jAcuZ4EPDb7Mzzx-po3Qn6Y',
    appId: '1:770152763239:ios:9775debb685e28371ca9c2',
    messagingSenderId: '770152763239',
    projectId: 'devolveolivro',
    storageBucket: 'devolveolivro.appspot.com',
    iosClientId: '770152763239-ptk1c9t5nh4mt2dnod4ai9b1idgqa7ep.apps.googleusercontent.com',
    iosBundleId: 'com.example.trocalivros',
  );
}
